### PR TITLE
insta resolve PIL create tasks

### PR DESCRIPTION
**Pull request by joefitter**

### CODE REVIEW

**Comment by lennym** [comment]
It might be better to treat each case as a separate condition rather than continually adding to that one if statement.

**Comment by joefitter** [comment]
yeah I did that, then undid it as repeated the setting of the module state. Save those chars

**Comment by joefitter** [comment]
@lennym owzat?

**Comment by lennym** [comment]
Niiiice. 

I'll eventually want to go to model-by-model conditions, but this is fine for now. Just stops that one condition getting out of hand before it starts.

**Pull request merged**
