### PR TITLE
update project -> to inspectorate

### PR DESCRIPTION
**Pull request by joefitter**

### CODE REVIEW

**Comment by lennym** [comment]
The commit message and the code seem to have different ideas about what's supposed to happen. 

What's supposed to happen?

**Comment by joefitter** [comment]
my bad, better?

**Comment by lennym** [comment]
Given that neither the commit message nor the code have changed... 

`git commit --amend`

**Comment by joefitter** [comment]
ha, I just updated the PR title. Sorrybox

**Pull request merged**
