### PR TITLE
Transfer a PIL

### PR DESCRIPTION
**Pull request by wheelsandcogs**

### CODE REVIEW

**Comment by lennym** [comment]
The establishment id that is created on this task is the id of the _receiving_ establishment, right?

**Comment by wheelsandcogs** [comment]
> The establishment id that is created on this task is the id of the _receiving_ establishment, right?

Correct.

**Comment by lennym** [comment]
Is the name of the outbound establishment stored/displayed anywhere?

There was some chat about showing that (and only that) as part of the task screen, but I can't see any code that does it.

**Comment by wheelsandcogs** [comment]
The incoming pages PR shows the establishment name on task view even when it's not a transfer.

**Comment by lennym** [comment]
Can we have some unit tests for this?

**Pull request merged**
