### PR TITLE
Bugfix - resolve pil grant if asru

### PR DESCRIPTION
**Pull request by joefitter**
* previously this would autoresolve and not leave a task behind

### CODE REVIEW

**Comment by lennym** [comment]
Is this going to break the content you just fixed?

**Comment by joefitter** [comment]
no, I tested it - we have one for resolved. It does mean we have a superfluous success message now

**Comment by lennym** [comment]
Nice. Apart from the "superfluous" bit, obvs.

**Comment by joefitter** [comment]
🤷

**Pull request merged**
